<?php

namespace Styde\Html\Tests;

use Mockery;
use Styde\Html\HtmlElement;

class FormBuilderTest extends TestCase
{
    /**
     * @var \Styde\Html\FormBuilder
     */
    protected $formBuilder;

    function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->formBuilder = $this->newFormBuilder();
    }

    /** @test */
    function it_adds_the_novalidate_attribute_to_all_forms()
    {
        $this->formBuilder->novalidate(true);

        $html = $this->formBuilder->open(['method' => 'GET']);

        $this->assertSame('<form method="GET" novalidate>', $html);
    }

    /** @test */
    function it_generates_time_inputs()
    {
        $html = $this->formBuilder->time('time')->render();

        $this->assertSame('<input type="time" name="time" value="">', $html);
    }
}